// MCP 23017 Extender pins
#define PIN_MCP_SPARE_A0 0
#define PIN_MCP_SPARE_A1 1
#define PIN_MCP_SPARE_A2 2
#define PIN_MCP_SPARE_A3 3
#define PIN_MCP_SPARE_A4 4
#define PIN_MCP_SPARE_A5 5
#define PIN_MCP_SPARE_A6 6
#define PIN_MCP_SPARE_A7 7
#define PIN_MCP_SPARE_B0 8
#define PIN_MCP_SPARE_B1 9
#define PIN_MCP_SPARE_B2 10
#define PIN_MCP_SPARE_B3 11
#define PIN_MCP_FAN_1 12
#define PIN_MCP_SPARE_B5 13
#define PIN_MCP_SPARE_B6 14
#define PIN_MCP_SPARE_B7 15

// ESP pins
#define PIN_ESP_SPARE_4 4
#define PIN_ESP_SPARE_5 5

#define PIN_ESP_PERIMETER_RELAY 12

#define PIN_ESP_SPARE_13 13

#define PIN_ESP_SPARE_14 14
#define PIN_ESP_SPARE_15 15

#define PIN_ESP_SPARE_16 16
#define PIN_ESP_SPARE_17 17

#define PIN_ESP_SPARE_18 18
#define PIN_ESP_SPARE_19 19

#define PIN_ESP_I2C_SDA 21
#define PIN_ESP_I2C_SCL 22

#define PIN_ESP_TEMP 23

#define PIN_ESP_SENDER_PERIMETER_IN1 25
#define PIN_ESP_SENDER_PERIMETER_IN2 26
#define PIN_ESP_SENDER_PERIMETER_PWM 27

#define PIN_ESP_SPARE_32 32
#define PIN_ESP_SPARE_33 33

#define PIN_ESP_RAIN 34
#define PIN_ESP_SPARE_35 35
#define PIN_ESP_SUPPLY_VOLTAGE 36
#define PIN_ESP_SPARE_39 39
