// Extender pins
#define PIN_MCP_KEYPAD_1 1
#define PIN_MCP_KEYPAD_2 2
#define PIN_MCP_KEYPAD_3 3
#define PIN_MCP_KEYPAD_4 4
#define PIN_MCP_FAN_1 5
#define PIN_MCP_FAN_2 6
#define PIN_MCP_MOTOR_CUT_HIGH_AMP 7
#define PIN_MCP_SPARE_1 8
#define PIN_MCP_SPARE_2 9
#define PIN_MCP_SPARE_3 10
#define PIN_MCP_MOTOR_CUT_LN1 11
#define PIN_MCP_MOTOR_CUT_LN2 12
#define PIN_MCP_MOTOR_LEFT_LN1 13
#define PIN_MCP_MOTOR_LEFT_LN2 14
#define PIN_MCP_MOTOR_RIGHT_LN1 15
#define PIN_MCP_MOTOR_RIGHT_LN2 16

// ESP pins
#define PIN_ESP_SONAR_CENTER 18
#define PIN_ESP_SONAR_RIGHT 19
#define PIN_ESP_SONAR_LEFT 13

#define PIN_ESP_MOTOR_CUT_PWM 25
#define PIN_ESP_MOTOR_LEFT_PWM 26
#define PIN_ESP_MOTOR_RIGHT_PWM 27

#define PIN_ESP_BUMPER_1 14
#define PIN_ESP_BUMPER_2 15

#define PIN_ESP_TILT_1 4
#define PIN_ESP_TILT_2 5

#define PIN_ESP_SCL 21
#define PIN_ESP_SDA 22
#define PIN_ESP_RX 17
#define PIN_ESP_TX 16

#define PIN_ESP_TEMP 23

#define PIN_ESP_RAIN A6
#define PIN_ESP_PERIMETER A3
#define PIN_ESP_AMP_CHARGE A7
#define PIN_ESP_BAT_VOLT A0
