name: PlatformIO CI

on: [push]

jobs:
  build_MOWER:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Rename file
        run: mv include/Credentials_definitions.h.sample include/Credentials_definitions.h
        working-directory: MOWER

      - name: Run PlatformIO
        run: platformio run
        working-directory: MOWER

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MOWER - Build Artifact
          path: MOWER/.pio/build/mower_esp32/firmware.bin

  build_BASE:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Rename file
        run: mv include/Credentials_definitions.h.sample include/Credentials_definitions.h
        working-directory: BASE

      - name: Run PlatformIO
        run: platformio run
        working-directory: BASE

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BASE - Build Artifact
          path: BASE/.pio/build/base_esp32/firmware.bin

  deploy_APP:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: APP

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: npm install
        run: npm install --verbose

      - name: Build
        run: npx webpack

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Website - Build Artifact
      #     path: BASE/.pio/build/base_esp32/firmware.bin